### PR TITLE
Add instructions on running ngrok to connect open source platform

### PR DESCRIPTION
**Pull request by DidierRLopes**
Let's wait on this being merged: https://github.com/OpenBB-finance/terminalpro/pull/901 - since otherwise I can't access citations from mobile.

### CODE REVIEW

**Comment by deeleeramone** [comment]
LGTM.

Screenshot 2024-10-28 at 4 06 47 PM

Question: All the Terminal docs are `.md` files, but the Platform docs are `.mdx`? Is there going to be a compatibility issue at some point?

**Review by deeleeramone — APPROVED** [review]
I didn't need to do step 4, but maybe that's because it was from the same machine.

**Comment by DidierRLopes** [comment]
> I didn't need to do step 4, but maybe that's because it was from the same machine.

Yup - @jose-donato had the same.

I'm gonna leave it bc it doesn't hurt if they add it and that way works for everyone just the same!

**Comment by DidierRLopes** [comment]
> LGTM.
> 
> Screenshot 2024-10-28 at 4 06 47 PM
> 
> Question: All the Terminal docs are `.md` files, but the Platform docs are `.mdx`? Is there going to be a compatibility issue at some point?

Not sure tbh - @jose-donato @andrewkenreich do u know about this?

**Comment by andrewkenreich** [comment]
@DidierRLopes ya its when we pulled them all over

**Pull request merged**
